### ISSUE TITLE
check

### ISSUE THREAD

**Issue by shamuel22** [georgeio/CoinbaseSDK-PHP#1]
{"errors":[{"id":"authentication_error","message":"invalid signature"}]}

**Comment by georgeio** [comment]
Hello @shamuel22 could you be a bit more descriptive as it will help resolve the issue raised. One of the parameters for calculating the signature used for a request is the API_SECRET. Can you confirm the value you got from Coinbase matches what you are passing as an argument when initializing the CoinbaseSDK-PHP class?

**Comment by shamuel22** [comment]
The value that I am sending matches correctly, I think there is an error with the capture of the signature

**Comment by shamuel22** [comment]
Coinbase made some changes, I'm not very familiar with the API I can not provide more

**Comment by georgeio** [comment]
<img width="982" alt="screen shot 2017-09-18 at 22 21 18" src="https://user-images.githubusercontent.com/17156631/30565269-80399e64-9c7c-11e7-9999-8595319659af.png">

@shamuel22 that is a screenshot of my postman calling the getAccountId method. I think you should look at your code. The library works and is still live on all the applications where i have it deployed. Sorry i can't ask to take a look at your code "_Note: You should never request API keys or secrets from other Coinbase users._ " -- Coinbase

**Comment by shamuel22** [comment]
I use simple

require_once "CoinbaseCustomSDK.php";
$cb_handle = new  CoinbaseCustomSDK('xxxxxxxxxx','xxxxxxxxx');

$name = "New Address";
echo $cb_handle->createNewAddress($name);

**Comment by georgeio** [comment]
The culprit is most likely your API_KEY and SECRET_KEY. Ensure they are correct and that you have them in the right order.

$cb_handle = new  CoinbaseCustomSDK('API_KEY', 'SECRET_KEY');

**Comment by shamuel22** [comment]
My API_KEY and SECRET_KEY are correct. Which extensions in PHP should I have enabled?

**Comment by georgeio** [comment]
CURL but i assume this is already enabled if not you would even be getting the error message from the coinbase API. The response shows you are hitting the endpoint just not providing the right information

**Comment by shamuel22** [comment]
Not work for me :(

**Comment by shamuel22** [comment]
Method to get new address is POST not GET, check line 81 of CoinbaseCustomSDK.php

**Comment by shamuel22** [comment]
Now work for me

**Comment by georgeio** [comment]
Good to know @shamuel22.

**Comment by georgeio** [comment]
You can star the repo if you find the library useful
